src/RTE.jl
=> Add RTE.jl

docs/make.jl, docs/src/RTE.md
=> Add RTE doc

src/rrtmgp/kernels/mo_reorder_kernels.jl, src/rte/kernels/mo_fluxes_broadband_kernels.jl, src/rte/kernels/mo_optical_props_kernels.jl
=> Translate 3 fortran files

src/fortranfuncs.jl, src/rte/kernels/mo_rte_solver_kernels.jl
In addition to `mo_rte_solver_kernels`, I've added a shared file for intrinsic fortran functions, which we can use across all modules.
=> Translate `mo_rte_solver_kernels`

src/rte/mo_optical_props.jl
Translates `mo_optical_props.jl`
=> [WIP] Translate `mo_optical_props.jl`

src/RTE.jl, src/rte/mo_source_functions.jl
=> Add mo_source_functions

src/rrtmgp/mo_util_string.jl
Translates the utility string module
=> Translate mo_util_string

src/RRTMG.jl, src/rrtmgp/mo_util_string.jl
=> Mo util string

src/RRTMG.jl, src/rrtmgp/mo_rrtmgp_constants.jl
=> Mo rrtmgp constants

src/JRRTMGP.jl, src/examples/rfmip-clear-sky/rrtmgp_rfmip_sw.jl, src/fortran_intrinsics.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl
Translates `rrtmgp_rfmip_sw`
Waiting on remaining modules. Several broken items (e.g., read), but will fix at runtime
=> Translate `rrtmgp_rfmip_sw`

Manifest.toml, docs/Manifest.toml, src/rte/mo_fluxes.jl, test/DataDeps.jl, test/runtests.jl
=> Refactor fluxes

README.md, src/extensions/mo_fluxes_byband.jl
=> Clean/update docs in mo_fluxes_byband

docs/src/index.md
=> References - pt 1

src/rte/mo_rte_sw.jl
Cleans up documentation/comments
Converts `if` statements to `@assert`'s
=> Cleanup mo_rte_sw

src/rte/mo_source_functions.jl
Refactor `mo_source_functions`
- Clean up comments
- Delete unused code
- Fix indentation
=> refactor mo_source_functions

src/rte/mo_rte_lw.jl
Clean up comments
If to assertion
Update docs
=> Refactor mo_rte_lw

src/rrtmgp/mo_gas_optics_rrtmgp.jl, src/rte/mo_util_array.jl
Remove zero_array function, clean up docs
=> Refactor mo_util_array

src/rte/kernels/mo_rte_solver_kernels.jl, src/rte/mo_rte_lw.jl, test/rfmip_clear_sky_lw.jl
Add longwave test, using different optical props, which should touch more code.
=> Add longwave test, using different optical props

src/rrtmgp/mo_rrtmgp_constants.jl
Clean up docs in `mo_rrtmgp_constants.jl`
=> Refactor mo_rrtmgp_constants

src/rte/kernels/mo_fluxes_broadband_kernels.jl
Clean up docs, utilize Julia intrinsics
=> Refactor mo_fluxes_broadband_kernels

src/examples/rfmip-clear-sky/mo_rfmip_io.jl
Clean up mo_rfmip_io docs, convert if to assertions
=> Refactor mo_rfmip_io

src/examples/mo_garand_atmos_io.jl, src/examples/mo_load_cloud_coefficients.jl, src/examples/mo_simple_netcdf.jl, test/adding.jl, test/mo_test_files_io.jl
Convert functions in `mo_simple_netcdf` to julia intrinsics
Move some untested functions to `adding.jl`
=> Remove unused functions/convert to intrinsics

src/extensions/cloud_optics/mo_cloud_optics.jl, test/allsky.jl
Add all-sky test that uses Pade scheme
=> Add test that uses Pade scheme

src/extensions/cloud_optics/mo_cloud_optics.jl
Remove finalize, unused functions, + bug fix; `:-11` -> `:-1:1`, if to assert
=> Clean up cloud optics

src/rte/kernels/mo_optical_props_kernels.jl, test/PartialImplementations.jl, test/mo_optical_props_kernels_nstream.jl, test/runtests.jl
As the `nstream` implementation is partial, this code has been moved to the test directory, so that it's still compiled.
=> Move nstream kernels to test

src/rrtmgp/mo_gas_concentrations.jl
Clean up docs
Convert if to assert
=> Clean up mo_gas_concentrations

src/rrtmgp/kernels/mo_gas_optics_kernels.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl, src/rte/kernels/mo_rte_solver_kernels.jl, src/rte/mo_fluxes.jl, src/rte/mo_rte_lw.jl, src/rte/mo_rte_sw.jl
- Adds @inbounds
- Adds type restrictions to kernels
- reduces allocations
- Convert some `zeros(...)` to `Array{}(undef,...)`
=> Improve performance

src/fortran_intrinsics.jl, src/rte/mo_optical_props.jl
Phasing out some of the Fortran intrinsics / debugging functions
=> Trim unused functions in FortranIntrinsics

test/runtests.jl
Accidentally removed some tests, adding them back in here
=> Adds allsky and clearsky lw tests back to runtests

src/extensions/cloud_optics/mo_cloud_optics.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl, src/rte/mo_optical_props.jl, src/rte/mo_rte_lw.jl, test/allsky.jl, test/mo_test_files_io.jl, test/rfmip_clear_sky_sw.jl
Composes `ty_optical_props` by sharing `ty_optical_props_base`, which has been made immutable.
=> Make ty_optical_props_base immutable

OriginalRRTMGP/AutoRunRRTMGP.jl, OriginalRRTMGP/CleanRRTMGP.jl, OriginalRRTMGP/ConfigRRTMGP.jl, OriginalRRTMGP/TarNewRefernceData.jl
Fixes a few missed rename changes (JRRTMGP -> RRTMGP)
=> Fix JRRTMGP -> RRTMGP in running original RRTMGP

src/examples/rfmip-clear-sky/mo_rfmip_io.jl, src/rrtmgp/mo_gas_concentrations.jl, test/allsky.jl, test/mo_test_files_io.jl
- Removes unused functions, and `if` branches in `mo_gas_concentrations.jl`
- Makes `ty_gas_concs` immutable
=> Remove partial initialization

src/examples/rfmip-clear-sky/mo_rfmip_io.jl, src/fortran_intrinsics.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl, src/rte/mo_optical_props.jl, src/rte/mo_source_functions.jl, test/mo_cloud_sampling.jl
Simplifies logic in
- `determine_gas_names`
=> Simplify logic

src/examples/mo_load_cloud_coefficients.jl, src/extensions/cloud_optics/mo_cloud_optics.jl, test/allsky.jl
- Adds sub-structs `LookUpTable`/`PadeMethod` to `ty_cloud_optics`
=> Add structure to cloud_optics

src/rrtmgp/mo_gas_optics_rrtmgp.jl
Makes several properties of `ty_gas_optics_rrtmgp` mutable / computed before initialization:
- `AuxVars`
- `AtmosVars`
- `kmajor`
- `is_key`
- `gpoint_flavor`
- `flavor`
- `gas_names_present `
=> Move towards immutable `ty_gas_optics_rrtmgp`

src/rrtmgp/mo_gas_optics_kernels.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl
- Removes some indexes passed through function calls
- Clean up some docs
- Reduce use of indexes
=> Remove some indexes passed into funcs

src/examples/mo_load_coefficients.jl, src/rrtmgp/mo_gas_optics_rrtmgp.jl
- Adds type restrictions
- Fix argument ordering/passing
- update docs
=> Add docs and type restrictions

src/examples/LoadCoefficients.jl, src/rrtmgp/GasConcentrations.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/GasOptics_kernels.jl
Replaces #148, taking smaller steps
=> Add InterpolationCoefficients struct

docs/src/RRTMGP/GasOptics.md, src/examples/LoadCoefficients.jl, src/examples/RFMIPIO.jl, src/rrtmgp/GasConcentrations.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/GasOptics_kernels.jl, src/rte/OpticalProps.jl, test/TestFilesIO.jl, test/allsky.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_sw.jl
- Removes stale docs
- Adds some type restrictions
- Changes `AuxVars` -> `GasOpticsAux`
=> Remove stale docs, add type restrictions

ReadInputData/LoadCoefficients.jl, ReadInputData/ReadInputs.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/Reference.jl, test/allsky.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_sw.jl
- Re-configure function arguments
- Add type restrictions
- Remove some unused functions for `Reference`, move remaining to `Reference.jl`
- Rename some variables
=> Refactor GasOptics

ReadInputData/ReadInputs.jl, docs/src/RRTMGP/GasConcs.md, docs/src/RTE/OpticalProps.md, src/rrtmgp/GasConcentrations.jl, src/rrtmgp/GasOptics.jl, test/allsky.jl
- Updates docs
- Removes unused variables
- Cleans up some calls to get/set vmr
=> Update docs, remove unused vars

src/RRTMGP.jl, src/rte/AngularDiscretizations.jl, src/rte/FluxesBroadBand.jl, src/rte/RTESolver.jl, src/rte/kernels/RTESolver_kernels.jl, test/rfmip_clear_sky_lw.jl
- Adds angular discretization (Gauss quadrature)
- Adds type restrictions to `FluxesBroadband`
=> Add `AngularDiscretizations`

src/extensions/CloudOptics.jl, test/allsky.jl
- Adds `CloudOpticalProps` type
- Adds/fixes docs to CloudOptics
- Adds back in error checking on cloud optics parameters
=> Add CloudOpticalProps type

ReadInputData/LoadCoefficients.jl, src/FortranIntrinsics.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/GasOptics_kernels.jl
Adds per-grid-point computation of:
=> Adds per-grid-point computations of spectral optical depth

src/extensions/CloudOptics.jl, src/rrtmgp/AtmosphericStates.jl, src/rrtmgp/GasConcentrations.jl, src/rte/AngularDiscretizations.jl, src/rte/Fluxes.jl, src/rte/RadiativeBoundaryConditions.jl
=> Add type restrictions, fix docs

src/rrtmgp/AtmosphericStates.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/GasOptics_kernels.jl
- Moves `tropo` and `tropo_lims` to `AtmosphericState`
This was done because `tropo_lims` is computed based on `minloc` (`findfirst`) over layers, which is better suited in the `AtmosphericState` constructor, rather than the compute kernels so that the compute kernels can operate per grid point.
=> Move `tropo` and `tropo_lims` to `AtmosphericState`

src/Utilities.jl, src/rte/OpticalProps.jl
=> Remove unused functions

src/MeshOrientations.jl, src/rrtmgp/AtmosphericStates.jl, src/rrtmgp/GasOptics.jl, src/rrtmgp/GasOptics_kernels.jl, src/rte/RTESolver.jl, src/rte/RTESolver_kernels.jl, test/allsky_pgp.jl, test/rfmip_clear_sky_lw_pgp.jl
This gives better control over the mesh orientation / indexing, and will allow us to merge if branches in the RTE solver.
=> Refactor MeshOrientation

README.md
This table format is more mobile-friendly! 📱
=> Reshape README table

src/rte/RTE.jl, src/rte/RTESolver.jl, src/rte/RTESolver_kernels.jl, src/rte/RadiativeBoundaryConditions.jl
- Adds an RTE structure to dispatch on solving the RTE
- Convert some routines in RTE to per-grid-point with wrapper functions
=> Add RTE structure

README.md, docs/src/MathFormulation.md, src/rte/RTE.jl, src/rte/RTESolver_kernels.jl
- Updates docs / mathematical formulation
- Adds acknowledgments
=> Update docs and README

src/rte/RTESolver_kernels.jl
- Makes more methods point-wise
- Puts contents of `lw_solver_noscat!` into `solve!(rte::RTELongWaveNoScattering{FT,I}, ...)`
We were able to fuse some operations and remove some temporary arrays due to removing `lw_solver_noscat!`, resulting in some noticeable performance improvements!
=> Make more point-wise ops

.dev/.gitignore, .dev/Project.toml, .dev/format.jl
To apply locally,
```
julia .dev/format.jl
```
=> Add formatter scripts

src/rrtmgp/AtmosphericStates.jl, test/allsky.jl, test/allsky_pgp.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_lw_pgp.jl, test/rfmip_clear_sky_sw.jl, test/rfmip_clear_sky_sw_pgp.jl, test/test_allsky.jl, test/test_rfmip_clear_sky_lw.jl, test/test_rfmip_clear_sky_sw.jl
* Removed Compile_first option in tests
* Replaced "spread" function in get_col_dry function in src/rrtmgp/AtmosphericStates.jl
=> Removed Compile_first option in tests

ReadInputData/ReadInputs.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_lw_pgp.jl, test/rfmip_clear_sky_sw.jl, test/rfmip_clear_sky_sw_pgp.jl, test/test_rfmip_clear_sky_lw.jl
This PR removes blocks from the data layout.
=> Remove blocks from data layout.

test/PostProcessing.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_lw_1c.jl, test/rfmip_clear_sky_sw.jl, test/rfmip_clear_sky_sw_pgp.jl
Bug fix in the "if loop" in test, that checks for TwoStream/Scalar optical props constructor.
=> Revised tests to use relative errors.

src/gray_optics/GrayAtmos.jl, src/gray_optics/GrayAtmosphericStates.jl, src/gray_optics/GrayUtils.jl, src/gray_rte/GrayRTESolver.jl, src/gray_rte/GrayRTESolverKernels.jl, test/gray_atm.jl
Removed top_at_1 flag, indicating the mesh orientation. The supported orientation will be along positive altitude axis (top_at_1 = false).
=> Removed top_at_1 flag

.buildkite/ci-pipeline.yml, .github/workflows/OS-UnitTests.yml, Manifest.toml, Project.toml, src/gray_optics/GrayAngularDiscretizations.jl, src/gray_optics/GrayAtmos.jl, src/gray_optics/GrayAtmosphericStates.jl, src/gray_optics/GrayBCs.jl, src/gray_optics/GrayFluxes.jl, src/gray_optics/GrayOptics.jl, src/gray_optics/GraySources.jl, src/gray_optics/GrayUtils.jl, src/gray_rte/GrayRTESolver.jl, src/gray_rte/GrayRTESolverKernels.jl, test/gray_atm.jl
Revised RTE kernel interfaces to accept structs as arguments, based on Adapt.jl.
=> Revised RTE kernel interfaces

.github/workflows/CodeCov.yml
This PR adds codecov, via a GHA, back into the repo.
=> Add codecov GHA

.buildkite/ci-pipeline.yml, .github/workflows/docs.yml, bors.toml, docs/make.jl, docs/src/MathFormulation.md, docs/src/MeshOrientation.md, docs/src/OpticalProps.md, docs/src/RRTMGP/AtmosphericStates.md, docs/src/RRTMGP/GasConcs.md, docs/src/RRTMGP/GasOptics.md, docs/src/RRTMGP/Gases.md, docs/src/RRTMGP/ReferenceStates.md, docs/src/RRTMGP/SourceFunctions.md, docs/src/RTE/AngularDiscretizations.md, docs/src/RTE/BoundaryConditions.md, docs/src/RTE/Fluxes.md, docs/src/RTE/RTESolver.md
=> Fix broken documentation, make strict

Manifest.toml, src/optics/AngularDiscretizations.jl, src/optics/Fluxes.jl, src/optics/GrayAtmosphericStates.jl, src/optics/Optics.jl, src/optics/Sources.jl, src/optics/Vmrs.jl, test/clear_sky.jl, test/gray_atm.jl, test/read_all_sky.jl, test/read_rfmip_clear_sky.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_sw.jl
Authored-by: skandalaCLIMA <skandala@caltech.edu>
=> Update to CUDA 3.4.1

Manifest.toml, Project.toml, src/optics/CloudOptics.jl, src/optics/GasOptics.jl, src/optics/GrayOpticsKernels.jl, src/optics/GrayUtils.jl, src/optics/Optics.jl, src/rte/RTESolver.jl, src/rte/RTESolverKernels.jl
Replace UnPack with native Julia destructuring syntax
=> Replace UnPack with native Julia destructuring syntax

src/optics/Optics.jl, src/rte/RTESolver.jl, test/all_sky.jl, test/clear_sky.jl
Merge GPU kernels for optics calculations and RTE solver.
=> merge gpu kernels

.github/workflows/TagBot.yml, Project.toml, src/Device.jl, src/optics/Optics.jl
This release includes a major restructuring of GPU kernels to provide significant speedup on CUDA devices.
=> Bump to v0.3.0.

examples/Manifest.toml, gpuenv/Manifest.toml
This PR fixes the Manifest files that were added in #286.
=> Develop RRTMGP in examples and gpu envs

.github/workflows/CodeCov.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/docs.yml, README.md, docs/make.jl
This PR renames master -> main and adds some doc deployment kwargs.
=> Rename master -> main

Project.toml, src/optics/AtmosphericStates.jl, src/optics/CloudOptics.jl, src/optics/Optics.jl, src/rte/RTESolver.jl, test/all_sky.jl, test/read_all_sky.jl, test/read_rfmip_clear_sky.jl
Builds McICA-sampled cloud mask from cloud fraction data for maximum-random overlap
(State concisely the benefits to be derived from and the risks associated with this PR)
- Fixes #301 
- Closes #301
=> Build McICA-sampled cloud mask from cloud fraction data

src/optics/AtmosphericStates.jl, src/optics/CloudOptics.jl, test/read_all_sky.jl
Implement the RRTMG version of the maximum-random overlap algorithm.
- Fixes #312 
- Closes #312
=> Use RRTMG version of  maximum-random overlap algorithm.

Project.toml
Bump version to v0.6.0
New release contains updates related to implementation of cloud fraction.
Benefits: It uses the overlap assumption in RRTMG, which is more commonly used in GCMs.
Risks: It still needs physical tests.
=> Bump version to v0.6.0

src/optics/CloudOptics.jl
When comparing random number with 1 - cloud fraction, we change the condition > to >= to address the edge case that cloud fraction is 1 but random number is 0.
=> Address edge cases in cloud sampling

docs/make.jl, docs/src/optics/Optics.md
=> Make docs strict

docs/Manifest.toml, docs/Project.toml, docs/bibliography.bib, docs/make.jl, docs/src/MathFormulation.md, docs/src/RTE.md, docs/src/References.md, docs/src/index.md
Add overview and RTE to the docs. Closes #328. Note that I was trying to follow the code when there are discrepancies between the code and the paper. Please click on `documenter/deploy` at the bottom of this page to see the docs.
----
=> Add docs: overview and RTE equations

docs/bibliography.bib, docs/make.jl, docs/src/Optics.md
=> Add equations for gray radiation

docs/bibliography.bib, docs/src/Optics.md, src/optics/CloudOptics.jl
Closes #332  
Closes #333 
----
=> Add documentation for cloud optics

docs/src/optics/Optics.md, src/optics/GasOptics.jl, src/optics/Optics.jl, test/read_all_sky.jl, test/read_rfmip_clear_sky.jl
Fix typo in compute_col_dry_kernel!
----
=> Fix typo in compute_col_dry_kernel!

Project.toml
=> Bump to v0.8.0

Project.toml, examples/Manifest.toml, gpuenv/Manifest.toml
=> Update to CUDA 4

Project.toml, docs/Manifest.toml, examples/Manifest.toml, src/RRTMGP.jl, src/optics/AtmosphericStates.jl, src/optics/GrayAtmosphericStates.jl, src/optics/GrayUtils.jl, src/optics/Optics.jl, src/rte/RTESolver.jl
This PR updates the dependencies and switches to use `ClimaComms.@threaded`.
=> Update dependencies, use `ClimaComms.@threaded`

test/all_sky_utils.jl
This PR lowers the test allocation limit
=> Lower allocation limit

Project.toml, src/optics/CloudOptics.jl, src/optics/GrayAtmosphericStates.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/rte/RTESolver.jl
This PR sprinkles some `@inbounds` in some loops.
=> Add some `@inbounds`

.buildkite/pipeline.yml
This PR adds threaded benchmarks
=> Add threaded benchmarks

.buildkite/pipeline.yml, gpuenv/Manifest.toml, gpuenv/Project.toml
This PR adds a GPU benchmark to the test suite.
=> Add gpu benchmark

test/all_sky.jl, test/all_sky_utils.jl, test/read_all_sky.jl
Update all-sky tests to be able to use user prescribed number of columns
----
=> Update all_sky tests

.buildkite/pipeline.yml, perf/benchmark.jl, test/all_sky.jl, test/all_sky_utils.jl, test/clear_sky.jl, test/clear_sky_utils.jl, test/gray_atm.jl, test/gray_atm_utils.jl, test/read_all_sky.jl, test/read_rfmip_clear_sky.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_sw.jl
This PR:
- Applies some small fixes for Float32
- Adds a benchmark test that runs with Float32
This is a step towards #337.
=> Apply fixes for Float32

Project.toml, docs/Manifest.toml, docs/make.jl, examples/Manifest.toml, gpuenv/Manifest.toml, src/optics/LookUpTables.jl
This PR updates the CUDA compat to include 5.0, and updates the dependencies.
=> Update CUDA compat and dependencies.

examples/Project.toml, gpuenv/Project.toml, src/optics/LookUpTables.jl, test/Project.toml
NCDatasets v0.13.0 seems to have introduced some behavioral changes, breaking some tests. Compat entry restricts the version of NDDatasets used till appropriate updates can be made to codebase.
----
=> Add compat for NCDatasets.

.github/workflows/CodeCov.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/OS-UnitTests.yml, .github/workflows/docs.yml, bors.toml
Migrating from Bors to GitHub Merge queue + Buildkite
----
=> Migrating from Bors to GitHub Merge queue + Buildkite

Project.toml, docs/Manifest.toml, examples/Manifest.toml, src/optics/CloudOptics.jl
Tag v0.10.0
Update dependencies
Update doc string for `build_cloud_mask`
----
=> Tag v0.10.0

.buildkite/pipeline.yml, examples/Manifest.toml, gpuenv/Manifest.toml
Update Julia, CUDA versions in Buildkite pipeline
----
=> Update Julia, CUDA versions in Buildkite pipeline

docs/src/optics/Optics.md, src/optics/CloudOptics.jl, src/optics/OpticsUtils.jl
Simplify 2-stream increment function
----
=> Simplify 2-stream increment function

docs/src/optics/LookUpTables.md, src/optics/CloudOptics.jl, src/optics/GasOptics.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/optics/OpticsKernels.jl, src/rte/RTESolver.jl, test/all_sky_utils.jl
Split up `LookUp table` and `Pade` cloud optics tables.
----
=> Split up `LookUp table` and `Pade` cloud optics tables.

docs/src/RTE.md, docs/src/rte/RTESolver.md, src/optics/Sources.jl, src/rte/RTESolver.jl, src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl, test/gray_atm_utils.jl
Restructure 2-stream shortwave solver
----
=> Restructure 2-stream shortwave solver

docs/src/RTE.md, docs/src/rte/RTESolver.md, src/rte/shortwave2stream.jl
=> update shortwave RTE docs

src/optics/Vmrs.jl, test/read_all_sky.jl
Swap `vmr` dimensions
Use first dimension for `gas-id`
----
=> Swap `vmr` dimensions

src/optics/GasOptics.jl
Replace `fld` with `unsafe_trunc`
----
=> Replace `fld` with `unsafe_trunc`

src/optics/GrayOpticsKernels.jl, src/optics/Optics.jl, src/optics/RTE.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl
Simplify optics parameter types
----
=> Simplify optics parameter types

src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl
Simplify parameter types for RTE shortwave solver
----
=> Simplify parameter types for RTE shortwave solver

docs/src/optics/Optics.md, src/optics/GasOptics.jl, src/optics/Optics.jl
Split LW & SW gas optics functions
----
=> Split LW & SW gas optics functions

docs/src/RTE.md, docs/src/optics/Optics.md, docs/src/rte/RTESolver.md, src/optics/GrayOpticsKernels.jl, src/optics/Optics.jl, src/optics/Sources.jl, src/rte/RTESolver.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl, test/gray_atm_utils.jl
Restructure longwave RTE solver to eliminate some temporary storage and
to reduce reads and writes to global memory
----
=> Restructure longwave RTE solver

.buildkite/pipeline.yml, .github/workflows/CodeCov.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/OS-UnitTests.yml, Project.toml
Updates to Julia v1.10 as well
=> New minor release

src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave2stream.jl, test/all_sky_utils.jl, test/clear_sky_utils.jl
Fix `net_flux` calculation for shortwave solver.
----
=> Fix `net_flux` calculation for shortwave solver.

docs/src/optics/LookUpTables.md, src/optics/GasOptics.jl, src/optics/LookUpTables.jl, test/all_sky_utils.jl, test/clear_sky_utils.jl
Restructure minor optics computation
----
=> Restructure minor optics computation

src/optics/Optics.jl
Update `OneScalar` and `TwoStream` structs
----
=> Update `OneScalar` and `TwoStream` structs

src/optics/Optics.jl, src/optics/RTE.jl, src/optics/Sources.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave2stream.jl
Restructure Source structs to provide contiguous data access
----
=> Restructure Source structs

docs/src/optics/Optics.md, src/optics/CloudOptics.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, test/read_all_sky.jl
Restructure LookUpCld to reduce metadata size
----
=> Restructure LookUpCld to reduce metadata size

src/optics/GasOptics.jl
Rewrite code in some branching statements to ease register pressure in `GasOptics.jl`
----
=> Ease register pressure in `GasOptics.jl`

src/optics/Optics.jl
Split shortwave optics function for `OneScalar` and `TwoStream` cases
----
=> Split shortwave optics function

docs/src/optics/LookUpTables.md, src/optics/CloudOptics.jl, src/optics/GasOptics.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave2stream.jl, test/all_sky_utils.jl, test/clear_sky_utils.jl, test/read_all_sky.jl, test/read_rfmip_clear_sky.jl, test/rfmip_clear_sky_lw.jl, test/rfmip_clear_sky_sw.jl
Restructure LookUp tables
----
=> Restructure LookUp tables

Project.toml, changelog.md, docs/Manifest.toml, examples/Manifest.toml, gpuenv/Manifest.toml
=> Update to ClimaParameters v0.9

Project.toml, docs/Manifest.toml
This PR updates the Adapt compat, and upgrades the dependencies
=> Update Adapt compat

NEWS.md, Project.toml, changelog.md
=> Release v0.13

src/optics/GrayOpticsKernels.jl, src/optics/GrayUtils.jl, test/gray_atm_utils.jl
Some optimizations to gray LW simulation
----
=> Some optimizations to gray LW simulation

src/optics/Optics.jl
Update argument types for `compute_col_gas!`
----
=> Update argument types for `compute_col_gas!`

src/rte/RTESolver.jl, src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl, test/clear_sky_utils.jl, test/read_rfmip_clear_sky.jl, test/rfmip_clear_sky_sw.jl
Temporarily zero out SW Fluxes when zenith angle is > 90 deg - 2 * eps.
Ideally, this should be handled upstream to reduce branching and provide better load balance.
----
=> Zero out SW Fluxes when zenith angle is > 90 deg - 2 * eps

NEWS.md, Project.toml
=> New patch version

ext/RRTMGPCUDAExt.jl, ext/cuda/rte_longwave_1scalar.jl, ext/cuda/rte_shortwave_1scalar.jl, src/optics/Optics.jl, src/optics/RTE.jl, src/rte/RTESolver.jl, src/rte/longwave1scalar.jl, src/rte/shortwave1scalar.jl
Move `AngularDiscretization` to `NoScatLWRTE`
----
=> Move `AngularDiscretization` to `NoScatLWRTE`

src/optics/AngularDiscretizations.jl, src/rte/longwave1scalar.jl, test/runtests.jl
Update longwave secants and weights
----
=> Update longwave secants and weights

NEWS.md, Project.toml
=> Minor release `0.15.0`

Project.toml
=> Patch release `v0.15.1`

NEWS.md, Project.toml, docs/Manifest.toml
=> Release 0.16.0

docs/src/optics/AtmosphericStates.md, docs/src/optics/LookUpTables.md, docs/src/optics/Optics.md, ext/RRTMGPCUDAExt.jl, ext/cuda/optics.jl, ext/cuda/rte_longwave_1scalar.jl, ext/cuda/rte_longwave_2stream.jl, ext/cuda/rte_shortwave_2stream.jl, src/optics/AerosolOptics.jl, src/optics/AtmosphericStates.jl, src/optics/GasOptics.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/optics/OpticsUtils.jl, src/rte/RTESolver.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave2stream.jl, test/all_sky_with_aerosols.jl, test/all_sky_with_aerosols_utils.jl, test/read_all_sky_with_aerosols.jl, test/read_rfmip_clear_sky.jl, test/runtests.jl
Add support for aerosol optics.
----
=> Add support for aerosol optics.

NEWS.md, Project.toml, docs/Manifest.toml
=> Release 0.17.0

Project.toml, src/RRTMGP.jl
=> Remove ClimaParams dependency

Artifacts.toml, docs/make.jl, docs/src/ArtifactPaths.md, src/ArtifactPaths.jl, src/RRTMGP.jl, test/Artifacts.toml, test/Project.toml, test/all_sky_dyamond_gpu_benchmark.jl, test/all_sky_utils.jl, test/all_sky_with_aerosols_utils.jl, test/clear_sky_utils.jl, test/reference_files.jl
Move `Artifacts` to main project.
----
=> Move `Artifacts`

.buildkite/pipeline.yml, test/all_sky_utils.jl, test/all_sky_with_aerosols_dyamond_gpu_benchmark.jl, test/clear_sky.jl, test/clear_sky_dyamond_gpu_benchmark.jl, test/clear_sky_utils.jl, test/read_rfmip_clear_sky.jl
Add `clear-sky` and `all-sky with aerosols` GPU benchmarks
----
=> Add `clear-sky` and `all-sky with aerosols` GPU benchmarks

docs/src/optics/Optics.md, src/optics/AtmosphericStates.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/optics/aerosol_optics.jl, test/all_sky_with_aerosols_dyamond_gpu_benchmark.jl, test/all_sky_with_aerosols_utils.jl, test/read_all_sky_with_aerosols.jl
Add support for multiple aerosol types in a layer.
----
=> Add support for multiple aerosol types in a layer

NEWS.md, Project.toml
=> bump minor release

src/optics/AtmosphericStates.jl, src/optics/Optics.jl, src/optics/aerosol_optics.jl, test/read_all_sky_with_aerosols.jl
Compute `aero_mask` internally
----
=> Compute `aero_mask` internally

.buildkite/A100_pipeline/pipeline.yml
Add Clima (A100) pipeline
----
=> Add Clima (A100) pipeline

ext/cuda/optics.jl, src/optics/AtmosphericStates.jl, src/optics/GrayUtils.jl, src/optics/Optics.jl, src/optics/gas_optics.jl, src/optics/gray_atmospheric_states.jl, src/optics/gray_optics_kernels.jl, test/gray_atm_utils.jl, test/read_all_sky.jl, test/read_all_sky_with_aerosols.jl, test/read_rfmip_clear_sky.jl
Change data layouts for pressure, temperature, `col_dry` and relative humidity.
----
=> Change data layouts for pressure, temperature, col_dry and relative humidity

src/optics/Vmrs.jl, src/optics/gas_optics.jl, test/read_all_sky.jl, test/read_all_sky_with_aerosols.jl, test/read_rfmip_clear_sky.jl
Change data layout for `Vmr`
----
=> Change data layout for `Vmr`

docs/src/optics/Fluxes.md, ext/RRTMGPCUDAExt.jl, ext/cuda/rte_longwave_1scalar.jl, ext/cuda/rte_longwave_2stream.jl, ext/cuda/rte_shortwave_1scalar.jl, ext/cuda/rte_shortwave_2stream.jl, src/optics/Fluxes.jl, src/rte/longwave1scalar.jl, src/rte/longwave2stream.jl, src/rte/shortwave1scalar.jl, src/rte/shortwave2stream.jl, test/all_sky_utils.jl, test/clear_sky_utils.jl, test/gray_atm_utils.jl
=> Refactor `Fluxes`

perf/benchmark.jl, test/Project.toml, test/all_sky_dyamond_gpu_benchmark.jl, test/all_sky_reproducibility_test.jl, test/all_sky_utils.jl, test/read_all_sky.jl, test/runtests.jl
Add reproducibility test for non-trivial cloud fractions (work-in-progress)
----
=> Add reproducibility test for non-trivial cloud fractions

.github/workflows/downstream.yml
Add downstream tests for `ClimaAtmos.jl`.
----
=> Add downstream tests for `ClimaAtmos.jl`

.buildkite/A100_pipeline/pipeline.yml, .buildkite/pipeline.yml
Update modules for pipelines
----
=> Update modules for pipelines

NEWS.md, Project.toml
Bump new version so we can use the correct aerosol lookup table. I already tested that it works in ClimaAtmos.
----
=> bump patch version

NEWS.md, docs/src/Example.md, docs/src/Optics.md, docs/src/optics/LookUpTables.md, docs/src/optics/Optics.md, ext/RRTMGPCUDAExt.jl, ext/cuda/rte_longwave_2stream.jl, ext/cuda/rte_shortwave_2stream.jl, perf/benchmark.jl, src/optics/LookUpTables.jl, src/optics/Optics.jl, src/optics/cloud_optics.jl, src/rte/RTESolver.jl, src/rte/longwave2stream.jl, src/rte/shortwave2stream.jl, test/all_sky_with_aerosols.jl, test/all_sky_with_aerosols_dyamond_gpu_benchmark.jl, test/all_sky_with_aerosols_utils.jl, test/cloudy_sky.jl, test/cloudy_sky_dyamond_gpu_benchmark.jl, test/cloudy_sky_utils.jl, test/read_all_sky_with_aerosols.jl, test/read_cloudy_sky.jl, test/runtests.jl
=> remove pade approximation

README.md
=> add download badge
