CliMA/RRTMGP.jl

src/rrtmgp/kernels/mo_gas_optics_kernels.jl

Translated `mo_gas_optics_kernels`. @simonbyrne Here's the first file, but I know that [these lines](https://github.com/climate-machine/JRRTMGP/compare/mo_gas_optics_kernels?expand=1#diff-1c93cf0a86d4fa31e1075997f837afacR23-R45) need to be tested/fixed, for at the very least edge cases (e.g., the case of `any(mask) = false`).

Translate `mo_gas_optics_kernels`

---

src/fortran_intrinsics.jl
src/rte/mo_optical_props.jl

This adds `deallocate` back in, in order to preserve `allocated`-determined flow control.
Also fix in-place op assignments

Fix deallocate in mo_optical_props

---

src/rrtmgp/mo_rrtmgp_constants.jl

Translates `mo_rrtmgp_constants`
Note that `init_constants` was removed since it is never called

Translate mo_rrtmgp_constants

---

src/rrtmgp/mo_gas_optics_rrtmgp.jl
src/rte/kernels/mo_rte_solver_kernels.jl
src/rte/mo_rte_sw.jl
test/rfmip_clear_sky_sw.jl

Adds a shortwave rfmip clear sky test with `ty_optical_props_1scl` instead of `ty_optical_props_2str`

Add shortwave test with alternative optical props

---

RemainingFortranCode/mo_compute_bc.f90
RemainingFortranCode/mo_fluxes_bygpoint.f90
RemainingFortranCode/mo_heating_rates.f90
RemainingFortranCode/mo_rrtmgp_clr_all_sky.f90

Moves all code not yet translated to a separate folder. Also, converts comments back to f90 comments for readability.

Move remaining fortran code to separate folder

---

src/rrtmgp/mo_gas_concentrations.jl
src/rrtmgp/mo_gas_optics_rrtmgp.jl
test/allsky.jl

- Makes `get_vmr` non-allocating
- Removes `get_vmr` for rank 1 arrays, since `gas_conc` is only rank 2

Make get_vmr non-allocating

---

src/rte/mo_fluxes.jl
test/allsky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

- Makes `ty_fluxes_broadband` immutable
Note that `fluxes.flux_up/dn` are no longer views of `flux_up/dn`. Instead, `flux_up/dn` is assigned to `fluxes.flux_up/dn` after the solver is called.

Make `ty_fluxes_broadband` immutable

---

src/examples/mo_load_coefficients.jl
src/rrtmgp/mo_gas_optics_kernels.jl
src/rrtmgp/mo_gas_optics_rrtmgp.jl

- Passes `atmos::AtmosVars` instead of its properties to functions
- Remove arrays sizes from some input arguments

Simplify interfaces

---

src/rrtmgp/mo_gas_optics_kernels.jl
src/rrtmgp/mo_gas_optics_rrtmgp.jl

- Decomposes, and removes mutability of, `ty_gas_optics_rrtmgp` into two types to be dispatched

Remove `ty_gas_optics_rrtmgp` mutability

---

OriginalRRTMGP/TarNewRefernceData.jl
src/Misc.jl

Moves `compress_targz` outside of src/, since it's only used in OriginalRRTMGP/

Move `compress_targz` outside of `src`

---

docs/src/RRTMGP/GasOptics.md
src/examples/LoadCoefficients.jl
src/rrtmgp/GasOptics.jl

The original name is not really accurate and will cause confusion with `AtmosphericState` soon to come.

Rename `AtmosVars` to `GasOpticsVars`

---

src/rrtmgp/GasConcentrations.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/Reference.jl

- Removes conc_field
- Makes gas concs 3D arrays, rather than
- Moves Reference type into its own file, and adds type restriction

Refactor GasOptics

---

src/rrtmgp/GasOptics.jl
src/rrtmgp/GasOptics_kernels.jl
src/rte/OpticalProps.jl

- Removes some indexes passed as args
- Adds type restrictions to optical properties
- Convert loop to `repeat`
- Remove temp array `tlev_arr`

Remove some passed indexes

---

src/RRTMGP.jl
src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/Gases.jl
test/allsky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

- Adds `AtmosphericState`, and utilizes it for drivers
Some performance may be lost since this requires copying new `AtmosphericState`'s for each block in the clear sky drivers, but this nicely encapsulates some of the required input data, and will help simplify function interfaces.

Add AtmosphericStates

---

ReadInputData/LoadCoefficients.jl
docs/make.jl
docs/src/RRTMGP/GasOptics.md
docs/src/RRTMGP/ReferenceStates.md
src/RRTMGP.jl
src/Utilities.jl
src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/GasOptics_kernels.jl
src/rrtmgp/ReferenceStates.jl
src/rte/RTESolver.jl
test/allsky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

- Makes Reference its own module
- Moves error checking to `AtmosphericState` constructor
- Cleans up some docs
- Remove some unused function args in `GasOptics`

Move error checking to constructor

---

src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
test/rfmip_clear_sky_sw.jl

- Moves some variables, and corresponding error checking, to `AtmosphericState`
This simplifies some function interfaces but does add storage to the `AtmosphericState`, which may not be necessary.

Move some col_vars to `AtmosState`

---

src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
test/allsky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

- Moves `t_sfc` into `AtmosState`
- Moves `toa_src` out of `GasOptics`, since `toa_src` is more related to RTE than gas optics

Move `t_sfc` into `AtmosState`, and `toa_src` out of `GasOptics`

---

ReadInputData/LoadCoefficients.jl
docs/src/RRTMGP/GasOptics.md
src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/GasOptics_kernels.jl
src/rrtmgp/ReferenceStates.jl
src/rte/OpticalProps.jl
test/allsky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

- Splits `ReferenceState` into `ReferenceState` and `ReferenceStateProfiles`, where `ReferenceState` has no spatial information.
- Renames `InternalSourceGasOptics`->`KDistributionLongwave`
- Renames `ExternalSourceGasOptics`->`KDistributionShortwave`
- Adds some type restrictions
- Cleans up some documentation
- Adds `ReferenceStatePerGridPoint`
`AbstractGasOptics` (`KDistributionLongwave` and `KDistributionShortwave`) are now spatially independent and can be passed in by reference when called from CLIMA.

Split ReferenceState in k-dist, rename k-dists

---

docs/src/RRTMGP/GasOptics.md
src/rrtmgp/GasOptics.jl

- Renames Internal/External source gas optics to KDistribution long/shortwave.

Rename Internal/External GasOptics

---

src/extensions/CloudOptics.jl
src/rte/OpticalProps.jl
src/rte/kernels/OpticalProps_kernels.jl

- Refactors optical props kernels
- Removes unused Pade_eval in CloudOptics
- Reuse OpticalProps structures to clean interface in CloudOptics

Refactor CloudOptics and OpticalProps_kernels

---

ReadInputData/ReadInputs.jl
docs/src/RRTMGP/GasConcs.md
src/Utilities.jl
src/extensions/CloudOptics.jl
src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasConcentrations.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/GasOptics_kernels.jl
src/rrtmgp/Interpolation.jl
src/rte/FluxesByBand.jl
src/rte/OpticalProps.jl
src/rte/RTESolver.jl
src/rte/SourceFunctions.jl
src/rte/kernels/RTESolver_kernels.jl
test/allsky_pgp.jl
test/rfmip_clear_sky_lw_pgp.jl
test/rfmip_clear_sky_sw_pgp.jl
test/runtests.jl
test/test_allsky.jl
test/test_rfmip_clear_sky_lw.jl
test/test_rfmip_clear_sky_sw.jl

- Adds per grid point data structures:
- Adds `convert` methods to convert between struct of arrays and arrays of structs
- Adds new tests, which create per grid point data structures, and convert back and forth
- Adds some methods for per grid point data structures (in cloud optics)

Add per grid point structures, and convert methods

---

src/MeshOrientations.jl
src/RRTMGP.jl
src/rrtmgp/AtmosphericStates.jl
src/rrtmgp/GasOptics.jl
src/rrtmgp/GasOptics_kernels.jl
src/rrtmgp/ReferenceStates.jl
src/rte/FluxesBroadBand.jl
src/rte/FluxesByBand.jl
src/rte/OpticalProps.jl
src/rte/RTESolver.jl
src/rte/kernels/RTESolver_kernels.jl
test/allsky.jl
test/allsky_pgp.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_lw_pgp.jl
test/rfmip_clear_sky_sw.jl
test/rfmip_clear_sky_sw_pgp.jl

- Adds `MeshOrientation`, which contains `top_at_1` and `i_top`/`i_bot` depending on `top_at_1`'s value
- Simplify `apply_BC` implementation
- Removes `AtmosphericStatePGP` constructor, and some other unused functions
-

Add MeshOrientations

---

src/MeshOrientations.jl
src/rte/RTESolver_kernels.jl

- Removes `if` branches caused by the option of vertical orientation.
- Renames `mesh_orientation` in RTE to `mo`

Combine `top_at_1` logic

---

src/rte/RTESolver.jl
src/rte/RTESolver_kernels.jl
src/rte/RadiativeBoundaryConditions.jl

- Add ranks to BC structs
- Propagate optical properties instead of its fields
- Break down the equation in `lw_source_noscat`

Refactor RTE solver kernels

---

Project.toml
test/DataDeps.jl
test/runtests.jl

- Adds compat to Project.toml
- Removes DataDeps test, since it doesn't really do anything and recently [hung](https://dev.azure.com/climate-machine/RRTMGP.jl/_build/results?buildId=987&view=logs&j=93056758-5bfb-5750-f113-e720ddefdb4c) during the build.

Add compat to Project.toml

---

src/optics/Fluxes.jl
src/rte/RTESolver.jl
src/rte/RTESolverKernels.jl
test/all_sky.jl
test/clear_sky.jl
test/gray_atm.jl

Eliminate GPU to CPU copying for some arrays in RTE solver.
Merge multiple RTE GPU kernels into a single GPU kernel.

Eliminate GPU to CPU copy for some GPU arrays in RTE

---

.github/codecov.yml

This PR disables codecov review annotations (not posted to the PRs, but the line-by-line annotations).

Disable codecov annotations

---

Project.toml
parameters/create_parameters.jl
src/Parameters.jl
src/RRTMGP.jl
src/optics/AtmosphericStates.jl
src/optics/GrayAtmosphericStates.jl
src/optics/GrayOpticsKernels.jl
src/optics/GrayUtils.jl
src/optics/Optics.jl
src/optics/RTE.jl
src/optics/Sources.jl
test/all_sky.jl
test/clear_sky.jl
test/gray_atm.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

This PR updates RRTMGP.jl to use the new way of handling clima parameters, by defining `RRTMGPParameters` inside a new submodule, `Parameters`. This should be the last piece needed before upgrading ClimaAtmos.
It seemed like the simplest thing to do here was to add `param_set` to `SourceLWNoScat` and `SourceLW2Str`, so that `param_set` could propagate down to the compute kernel.

Use new way of handling climaparameters

---

src/optics/AtmosphericStates.jl
src/optics/CloudOptics.jl
test/all_sky.jl
test/clear_sky.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl
test/runtests.jl
test/runtests_gpu.jl

Refine/enlarge cloud_mask to be g-point and long/shortwave specific, in preparation for implementing cloud fraction support.
Enables support for cloud fraction.
- Fixes #297 
- Closes #297

Refine/enlarge cloud_mask to be g-point and long/shortwave specific

---

src/optics/AtmosphericStates.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl

Add cloud fraction input array to Atmospheric state
Allows user to prescribe cloud fraction for all-sky (cloudy) simulations.
- Fixes #299 
- Closes #299

Add cloud fraction to AtmosphericState

---

.buildkite/pipeline.yml

Enable parallel initialization of CPU and GPU environments in Buildkite pipeline.
(Clearly and concisely state the purpose of this PR)
This PR enables initialization of CPU and GPU environments to run simultaneously, saving build times.
- Fixes #
- Closes #

Enable parallel initialization of CPU and GPU environments in Buildkite

---

gpuenv/Artifacts.toml
test/Artifacts.toml

Update Artifacts to add reference data for cloud fraction tests
Full spectrum flux data for cloudy simulations is added to Artifacts. This reference data is intended for use with cloud fraction tests.
- Fixes #305 
- Closes #305

Update Artifacts to add reference data for cloud fraction tests

---

Project.toml

Bump version to v0.6.1, which contains a minor fix to address edge cases when sampling cloud fraction.

Bump version to v0.6.1

---

src/optics/GrayAtmosphericStates.jl
src/optics/GrayOpticsKernels.jl

Add SW optical depth calculation for gray radiation
----

add gray sw optical depth

---

docs/Manifest.toml
docs/src/Optics.md
docs/src/optics/AtmosphericStates.md
docs/src/optics/Optics.md
src/optics/AtmosphericStates.jl
src/optics/GrayAtmosphericStates.jl
src/optics/GrayOpticsKernels.jl
test/gray_atm.jl

Enable user-defined gray optical thickness calculations
----

Enable user-defined gray optical thickness calculations

---

src/optics/GasOptics.jl

Remove redundant op in compute_col_gas_kernel!
----

Remove redundant op in compute_col_gas_kernel!

---

Project.toml
src/optics/RTE.jl
src/rte/RTESolver.jl

This PR fixes a major latency issue on Julia 1.9 (per @vtjnash on slack)
> it is a constructor for a type with too many Union parameters
The fix is to remove several `Union` parameter types. I also took the opportunity to reduce the type space for `Solver`-- there is no need to have `I <: Int` and `FT` in the type space since `Int` will always resolve the same and `FT` can be grabbed from `eltype`s of member arrays.
Main:
```julia
julia> @time using RRTMGP
[ Info: Precompiling RRTMGP [a01a1ee8-cea4-48fc-987c-fc7878d79da1]
532.620944 seconds (517.19 M allocations: 140.311 GiB, 2.15% gc time, 0.16% compilation time: 86% of which was recompilation)
```
This PR:
```julia
julia> @time using RRTMGP
[ Info: Precompiling RRTMGP [a01a1ee8-cea4-48fc-987c-fc7878d79da1]
5.199173 seconds (5.78 M …
```

Fix Latency on julia 1.9

---

Project.toml

In order to add CUDA 4.2.0 to ClimaAtmos (regardless of whether it uses RRTMGP), we need RRTMGP to be compatible. So, this PR bumps the patch version for a new release.

Bump patch version for new release

---

test/aqua.jl

This PR updates and adds aqua tests.

Update aqua tests

---

src/optics/AtmosphericStates.jl
src/optics/GrayAtmosphericStates.jl
src/optics/GrayOpticsKernels.jl
test/gray_atm.jl

Change to use latitude and longitude in degrees in the input.
----

change input to degrees

---

src/optics/AngularDiscretizations.jl
src/optics/AtmosphericStates.jl
src/optics/GasOptics.jl
src/optics/GrayAtmosphericStates.jl
src/optics/LookUpTables.jl
src/optics/Optics.jl
src/optics/OpticsKernels.jl
src/optics/OpticsUtils.jl
src/optics/RTE.jl
src/optics/Sources.jl
src/rte/RTESolverKernels.jl
test/all_sky.jl
test/clear_sky.jl
test/gray_atm.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

There is no reason to have type parameters that we bound to concrete types:
```julia
julia> isconcretetype(UInt8)
true
julia> isconcretetype(Int)
true
```
This is similar to using `where {FT <: Float64}`, we might as well not have the type parameters, and not waste compiling a generic method with type assertions.
This PR removes these unnecessary type parameters. [xref](https://julialang.slack.com/archives/C03LD7K8HLN/p1683743629523789?thread_ts=1683740387.868789&cid=C03LD7K8HLN):
> FWIW, this bit also a bit odd: `where I<:Int64`, since this means I is either `Union{}` or `Int`, but seems like it would always just be an `Int`?
Unfortunately, this is a breaking change, but fixing upstream breakages with this should be easy.

Remove unnecessary type parameters

---

src/optics/CloudOptics.jl
src/optics/GasOptics.jl
src/optics/GrayOpticsKernels.jl
src/optics/Optics.jl
src/optics/OpticsKernels.jl

Based on the flame graphs, some functions seem to be suffering from the tuple splatting. This PR removes them for `glaycol` and just passes the two indices.

Do less splatting

---

src/optics/GasOptics.jl
src/rte/RTESolverKernels.jl

Based on the flame graph, the `exp` and `log` functions are a bit expensive and, since they are repeated, this PR precomputes and reuses the precomputed values.

Precompute expensive terms

---

src/RRTMGP.jl
src/optics/GrayOpticsKernels.jl
src/optics/GrayUtils.jl
src/optics/Optics.jl

Based on the flame graphs, we seem to be hitting this slow path (https://stackoverflow.com/questions/14687665/very-slow-stdpow-for-bases-very-close-to-1), same as what we hit in thermodynamics.
This PR adds `pow_fast(x, y) = exp(y * log(x))` to avoid the slow path.

Avoid slowpath in pow

---

docs/src/rte/RTESolver.md
perf/flame.jl
src/optics/LookUpTables.jl
src/optics/Optics.jl
src/rte/RTESolver.jl
src/rte/RTESolverKernels.jl

This PR removes some splatting / slurping of arguments, which the compiler cannot seem to infer well. Closes #365.
This is a clear improvement based on the benchmarks.

Remove splatting

---

perf/benchmark.jl

This PR adds interpolation into `@benchmark` statements, and use `CUDA.@async` for benchmarks.

Interpolate in benchmark

---

src/optics/Optics.jl

Its functionality has been replaced in `rte/RTESolver` by a single CUDA kernel launch for optical properties computation and rte solver.
----

remove compute_optical_props_CUDA!.

---

test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl
test/runtests.jl
test/runtests_gpu.jl

Add back stand-alone clear-sky lw & sw tests.
----

Add back stand-alone clear-sky lw & sw tests

---

src/rte/RTESolverKernels.jl

Add single precision support for RRTMGP
Trying: https://github.com/earth-system-radiation/rte-rrtmgp/pull/39 per issue https://github.com/CliMA/RRTMGP.jl/issues/337
----

Add single precision support for RRTMGP

---

Project.toml
examples/Project.toml
gpuenv/Project.toml
src/optics/LookUpTables.jl
test/Project.toml
test/clear_sky_utils.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl

Change syntax to get NC data

---

.github/workflows/docs.yml
docs/Manifest.toml
docs/Project.toml
docs/bibliography.bib
docs/make.jl

Modifying the `LOAD_PATH` messes up the JuliaHub mirrored docs.
Thanks to @mortenpi for the tip.
----

docs: don't append parent environment

---

src/optics/AtmosphericStates.jl
src/optics/CloudOptics.jl
src/rte/longwave2stream.jl
src/rte/shortwave2stream.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl

Refactor `build_cloud_mask!`.
----

Refactor `build_cloud_mask!`

---

src/optics/CloudOptics.jl
src/optics/OpticsKernels.jl

Add @inbounds to cloud optics computations
Restructure `compute_cld_props` interface
----

Restructure cloud optics computations

---

src/optics/BCs.jl
src/rte/shortwave1scalar.jl
src/rte/shortwave2stream.jl
test/all_sky_utils.jl
test/clear_sky_utils.jl
test/gray_atm_utils.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl
test/rfmip_clear_sky_sw.jl

Store `cos_zenith` instead of `zenith` in shortwave boundary conditions
----

Store `cos_zenith` instead of `zenith`

---

src/optics/GasOptics.jl
src/optics/LookUpTables.jl

Store `ln(p_ref)` instead of `p_ref` in lookup tables
----

Store `ln(p_ref)` instead of `p_ref` in lookup tables

---

src/optics/GasOptics.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave2stream.jl
test/all_sky_utils.jl
test/clear_sky_utils.jl
test/gray_atm_utils.jl
test/rfmip_clear_sky_lw.jl
test/rfmip_clear_sky_sw.jl
test/runtests.jl
test/runtests_gpu.jl

Tune tolerances in gas optics and RTE solver to reduce absolute and relative errors in single-precision calculations.
----

Fix single-precision relative and absolute errors

---

Artifacts.toml
Project.toml
artifacts/rrtmgp-lookup-data/.gitignore
artifacts/rrtmgp-lookup-data/Manifest.toml
artifacts/rrtmgp-lookup-data/Project.toml
artifacts/rrtmgp-lookup-data/README.md
artifacts/rrtmgp-lookup-data/create_artifact.jl
src/RRTMGP.jl
test/reference_files.jl

Adds script for creating RRTMGP lookup data tables artifact, and adds this to the package Artifacts.toml.
Fixes #401 (does not deal with test data, as this is not needed for the main project).
----

Add rrtmgp-lookup-data artifact

---

src/optics/GasOptics.jl
src/optics/LookUpTables.jl
src/optics/Optics.jl
src/optics/OpticsUtils.jl

Swap dimensions for `kmajor`, `kminor_upper`, `kminor_lower`, `planck_fraction`, `rayl_lower` and `rayl_upper` to move `igpt/ibnd` to the last dimension.
Update `interp1d`, `interp2d` and `interp3d` accordingly.
----

Swap dimensions for some lookup data

---

src/optics/AtmosphericStates.jl
src/optics/GrayAtmosphericStates.jl
src/optics/Optics.jl
src/optics/RTE.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl

Simplify type parameters for `AtmosphericState`
----

Simplify type parameters for `AtmosphericState`

---

src/optics/CloudOptics.jl
src/optics/GrayAtmosphericStates.jl
src/optics/GrayUtils.jl
src/optics/Optics.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave1scalar.jl
src/rte/shortwave2stream.jl

This PR:
- applies `always_inline = true` for the cuda launches
- Removes use of `StepRange`
as suggested in https://cuda.juliagpu.org/dev/tutorials/performance/

Always inline and remove use of StepRange

---

src/rte/shortwave2stream.jl

Add lower bound for cumulative optical thickness in 2-stream shortwave solver
----

Add lower bound for cumulative optical thickness

---

src/optics/AtmosphericStates.jl
src/optics/Optics.jl
test/read_all_sky.jl
test/read_rfmip_clear_sky.jl

Restructure data layout in `AtmosphericStates`
----

Restructure data layout in `AtmosphericStates`

---

.buildkite/pipeline.yml
test/all_sky_dyamond_gpu_benchmark.jl

Add `all-sky` DYAMOND GPU benchmark
----

Add `all-sky` DYAMOND GPU benchmark

---

src/optics/GrayOpticsKernels.jl

Replace exponential function in gray source calculations
----

Replace exponential function in gray source calculations

---

src/optics/GrayAtmosphericStates.jl

Add `getview` for `GrayAtmosphericState`
----

Add `getview` for `GrayAtmosphericState`

---

NEWS.md
Project.toml
docs/Manifest.toml
src/optics/LookUpTables.jl
test/Project.toml

closes https://github.com/CliMA/RRTMGP.jl/issues/482
bumps patch version so we can make a release with fix
tested in ClimaAtmos here: https://github.com/CliMA/ClimaAtmos.jl/pull/2968 ([passing build](https://buildkite.com/clima/climaatmos-ci/builds/18608))

handle FT of 0-dim Array

---

NEWS.md
Project.toml

0.13.4 was tagged in the `[0.13.4`](https://github.com/CliMA/RRTMGP.jl/tree/0.13.4) branch and reverts all the 0.13.3 changes.

Bump to 0.14.0

---

test/clear_sky.jl

Add non-scattering longwave test to `clear-sky` solver.
----

Add non-scattering longwave test to `clear-sky` solver

---

src/optics/CloudOptics.jl
src/optics/GasOptics.jl

Force optical thickness to be non-negative.
----

Force optical thickness to be non-negative

---

NEWS.md
ext/cuda/rte_shortwave_1scalar.jl
src/rte/shortwave1scalar.jl

Currently, `rte_sw_noscat_solve!` can break because the variable `lookup_sw_cld` is not defined. This PR replaces it with `nothing`

Fix noscatter shortwave solve

---

docs/src/optics/Optics.md
src/optics/Optics.jl
src/optics/optics_utils.jl
test/optics_utils.jl
test/runtests.jl

Support `1D` interpolation on non-uniform grid
----

Support `1D` interpolation on non-uniform grid

---

ext/cuda/rte_longwave_1scalar.jl
ext/cuda/rte_longwave_2stream.jl
ext/cuda/rte_shortwave_2stream.jl
src/optics/AtmosphericStates.jl
src/optics/Optics.jl
src/optics/aerosol_optics.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave2stream.jl
test/read_all_sky_with_aerosols.jl

Compute and store `aero_mask`.
This replaces the existing strategy where `aero_mask` is computed on the fly, resulting it being computed redundantly once per `g-point`.
----

Compute and store `aero_mask`.

---

ext/cuda/rte_longwave_1scalar.jl
ext/cuda/rte_longwave_2stream.jl
ext/cuda/rte_shortwave_1scalar.jl
ext/cuda/rte_shortwave_2stream.jl
src/optics/Fluxes.jl
src/optics/GrayUtils.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave1scalar.jl
src/rte/shortwave2stream.jl
test/all_sky_utils.jl
test/all_sky_with_aerosols_utils.jl
test/clear_sky_utils.jl
test/gray_atm_utils.jl
test/read_all_sky.jl
test/read_all_sky_with_aerosols.jl
test/read_rfmip_clear_sky.jl

Change data layout for fluxes.
Use `(ncol, nlev)` ordering instead of `(nlev, ncol)`.
----

Change data layout for fluxes.

---

src/optics/Optics.jl
src/optics/gray_optics_kernels.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave1scalar.jl
src/rte/shortwave2stream.jl
test/gray_atm_utils.jl

Change data layout for optical properties.
Use (ncol, nlev) ordering instead of (nlev, ncol).
----

Change data layout for optical properties.

---

src/optics/Optics.jl
src/optics/Sources.jl
src/optics/gray_optics_kernels.jl
src/rte/longwave1scalar.jl
src/rte/longwave2stream.jl
src/rte/shortwave2stream.jl

Change data layout for sources.
Use (ncol, nlev) ordering instead of (nlev, ncol).
----

Change data layout for sources.

---

src/optics/gas_optics.jl

Fix typo (dangling line) in `compute_relative_humidity_kernel!`
----

Fix typo in `compute_relative_humidity_kernel!`

---

src/optics/AngularDiscretizations.jl
src/optics/BCs.jl

Simplify type parameters for `AngularDiscretizations` and `BCs`.
----

Simplify type parameters for `AngularDiscretizations` and `BCs`.

---

NEWS.md
ext/cuda/rte_shortwave_1scalar.jl
ext/cuda/rte_shortwave_2stream.jl
src/rte/shortwave1scalar.jl
src/rte/shortwave2stream.jl

Prior to this commit, `flux_dn_dir` was not set in the two stream case for non-gray radiation, leading to incorrect values (whatever was in the memory at init). Now, the variable is accumulated over for ever g-point.

Fix flux_dn_dir not updated in all sky two stream

---

.github/workflows/downstream.yml

https://github.com/CliMA/ClimaCoupler.jl/pull/1033 added a `test/runtests.jl` file inside of the ClimaCoupler.jl `experiments/ClimaEarth/` directory. This sets up a coarse AMIP simulation and runs it for 2 timesteps. This is meant to be used in upstream packages as a way to ensure downstream compatibility. Note that it doesn't test long-term simulation stability.
This PR adds a downstream test for that environment in this package.

add coupler AMIP downstream test; add Julia 1.11 to downstream tests

---

NEWS.md
Project.toml
src/optics/LookUpTables.jl
src/optics/aerosol_optics.jl

co-authored-by: @charleskawczynski 
----

add different sizes for dust and sea salt

---

src/optics/aerosol_optics.jl

Right now, the aerosols are assigned bin 1 when the size is larger than the largest size bin. I think it is safer to assign them to the last size bin.
----

small fix for aerosol size bin

---

.buildkite/A100_pipeline/pipeline.yml

Add nsys profiler to GPU benchmarks
This pull request adds the `nsys` profiler to the GPU benchmarks in the `.buildkite/A100_pipeline/pipeline.yml` file. The changes involve modifying the `pipeline.yml` file to include the `nsight-systems/2024.6.1` module and adding `nsys profile` commands to the clear-sky, cloudy-sky, and all-sky DYAMOND GPU benchmark steps. This will enable profiling of these benchmarks using NVIDIA's Nsight Systems profiler.
* **Profiling**: Adds `nsys` profiling to GPU benchmarks to trace `nvtx`, `cuda`, and `osrt` events.
* **Module Update**: Includes the `nsight-systems/2024.6.1` module in the Buildkite pipeline.
* **Benchmark Commands**: Modifies benchmark commands to use `nsys profile` for generating profiling reports.
* **.buildkite/A100_pipeline/pipeline.yml**
* …

Add nsys profiler to GPU benchmarks

---

docs/src/rte/RTESolver.md
src/optics/Fluxes.jl
src/rte/RTESolver.jl
test/Project.toml
test/all_sky_with_aerosols_dyamond_gpu_benchmark.jl
test/all_sky_with_aerosols_utils.jl
test/aqua.jl
test/clear_sky_dyamond_gpu_benchmark.jl
test/clear_sky_utils.jl
test/cloudy_sky_dyamond_gpu_benchmark.jl
test/cloudy_sky_utils.jl

Pass metric scaling term to RRTMGP solver functions for use within the flux calculations to account for column expansion with altitude in deep-atmosphere configurations. 
Also fixes broken OS unit tests due to missing package in test env (`Random`)
Performance comparison: 
(main) :  https://buildkite.com/clima/rrtmgp-clima-a100-pipeline/builds/53
(PR) : https://buildkite.com/clima/rrtmgp-clima-a100-pipeline/builds/61
Degradation is approx 0.2%
e.g. build log: https://buildkite.com/clima/climacoupler-coarse-nightly-amip/builds/317/steps

Updates fluxes to apply scaled metrics in deep-atmosphere configurations
